virtual_file.go

Use bytes.Reader instead of bytes.Buffer in virtual files to support seek.
Hi,
Font awesome fonts in my project were not loading, so I looked at the source and found in https://golang.org/src/net/http/fs.go in serveContent that it uses Seek after reading some part of file to determine content type. So this pull request replaces bytes.Buffer with bytes.Reader to support seek. This fixes my font loading issue. It comes at the cost of not supporting write but I do not think that is needed.
Regards,
Domen

fix add support for seek in virtual files

---

box.go
builder/box.go
builder/builder.go
builder/builder_test.go
packr.go
packr/cmd/root.go
packr_test.go

Are you interested in adding compression? I took a stab at it, but am wondering if it should be a command line option?

gzip compress files

---

box.go
box_test.go
packr.go

* Prevent resources to be found from outside the scope of a box, so they
can't be available in the final box.

Ensure resources are fetch from inside the box

---

box.go
http_box_test.go

The handler created by `http.FileSystem` checks for `NotFound` related errors and returns `http.StatusNotFound` instead of `http.StatusInternalServerError`.
You can find the corresponding code [here](https://github.com/golang/go/blob/master/src/net/http/fs.go#L623).

Fix packr.Box when used as http.Filesystem

---

.travis.yml

It seems that Travis' Go Version is 1.9 but we only matched against 1.9.x. 
This change makes the last part of the version optional and Travis should pick up the deploy step when a release is tagged.
Closes #25

Also match Go version 1.9 next to 1.9.x

---

builder/box.go

I was probably doing something that wasn't intended, but anyways, I had -packr files in a box directory, and they just kept getting larger.

ignore -packr.go files in box directory

---

box.go
box_test.go
packr_test.go

On the first call to find(), index the directories in the box.
When returning a virtual directory, first check to see if that
directory exists, if not return a not found error.
This will cause http.FileServer to return a 404 on a
directory that does not exist in the box.
Note: The directory index is delayed until the first find() to make it work with the virtualBox used in testing, as well as to get around any race conditions of init methods.

rfc: error on virtual directory that does not exist

---

example/example.go

When you run `go get -u github.com/gobuffalo/packr/...` on a server that does not have the `gcc` compiler installed the go get will fail with the error below. This is because `github.com/gobuffalo/buffalo/render` has a dependency on it. If you run `go list -f '{{ .Deps }}' github.com/gobuffalo/buffalo/render ` you can see it in the output.
```shell
exec: "gcc": executable file not found in $PATH
```
This makes it hard to install from source on a ci servers that do not need the `gcc` compiler at all. Since it is only for the example folder I think it is okay to modify it not to break this.

Remove buffalo/render dependency

---

box.go

strings.TrimPrefix can give the wrong result with case-insensitive
paths. filepath.Rel usually works better.

Fix relative path finding (gobuffalo/buffalo#982)

---

builder/builder.go

Fixes #56 by adding .idea directory to skipped directories for Builder.

Added .idea directory to base names skipped by Builder's Run() method

---

builder/tmpl.go

This is a simple change to make `gofmt` hapyp with the generated code.
The only issue was the last `}` which was badly aligned.

fix: generated gofmtd code

---

builder/tmpl.go

The generated files contained an extra tab character before every instance of `packr.PackJSONBytes`. This removes the extra tab such that the generated files are compliant with gofmt.

Make generated files comply with gofmt

---

builder/builder.go

When packr is run in a git submodule, where `.git` is a file containing just a line
```
gitdir: ../.git/modules/my-sub-module
```
it causes an error during `filepath.Walk`, because it tries to return `SkipDir`, whereas the entry is a file but not a dir. In that case, we should instead return nil, so that the walk will move on to another file. If it returns `SkipDir`, the entire walk will fail with an error, and subsequent files and/or directories will all be ignored.

Fix issue with an ignored name being a file.

---

README.md

I have updated the README about how to cover certain use cases.
This references #75 as well as #85 
🙏 
Compiling with `.go` files requires absolute paths
Having multiple releases in a directory is problematic
Using `mv` to move the built binary without the `-o` flag to the target dir mitigates said issues.

Add sections in README about portable releases

---

v2/jam/store/disk.go

prevents bad replacement of imports starting with prefix matching GoPath

disk Generate() do import replacement on GoPaths before SrcDirs

---

v2/jam/store/disk.go

When on Go v1.12, Consult `go env GOMOD` To Find Location of go.mod

---

box.go

Fixes: https://github.com/gobuffalo/packr/issues/154
Adds a deferred close to the `gzip.Reader` to avoid file descriptor leak.

Issue-154: unclosed gzip.Reader

---

v2/jam/parser/finder.go

check file is not a directory when returned as a file

---

v2/box.go
v2/box_test.go

When running the tests locally I keep getting the following error. I'm reverting this PR until the tests pass cleanly.
```
--- FAIL: Test_Box_Open (0.00s)
require.go:157: 
Error Trace:	box_test.go:216
Error:      	Not equal: 
expected: true
actual  : false
Test:       	Test_Box_Open
Messages:   	stat.IsDir() != true for path "/baz"
```

Revert "box.Open: Do not call file.NewFileR when IsDir true, fix #198"

---

v2/box.go
v2/box_test.go
v2/file/resolver/disk.go

This PR improves file resolution in certain corner cases.

Improve file resolution with the Disk and fallback resolver

---

v2/box.go
v2/box_test.go
v2/file/resolver/disk.go

This fixes an issue with the test cases where macOS would resolve paths differently.

Improve test cases for file resolution

---

README.md

Makes `github.com/markbates/pkger` a link. Might save a click or two for folks on their way.

README: linkify migration target suggestion

---

packr/cmd/version.go
v2/packr2/cmd/version.go

When running `packr version`, it should print the version on it's own line.
Current behavior:
```
$ packr version
v2.5.3$
```
New behavior:
```
$ packr version
v2.5.3
$
```
When checking the recommended behavior against [Cobra](https://github.com/spf13/cobra), their example uses `Println`, as well.
```
var versionCmd = &cobra.Command{
Use:   "version",
Short: "Print the version number of Hugo",
Long:  `All software has versions. This is Hugo's`,
Run: func(cmd *cobra.Command, args []string) {
fmt.Println("Hugo Static Site Generator v0.9 -- HEAD")
},
}
```

Print version on new line

---

README.md

There is no such a `FindBytes` method implemented for `Box`. I suppose it should be `Find`, according to:
https://github.com/gobuffalo/packr/blob/c6a5045204dacffbe11d9f6c68485ae7e7fe3d19/box_test.go#L27

Fix a typo in README: FindBytes -> Find

---

v2/go.mod
v2/go.sum

This PR updates github.com/karrick/godirwalk from v1.15.3 to v1.15.8 to adopt the upstream fix https://github.com/karrick/godirwalk/pull/52.
Fixes https://github.com/gobuffalo/packr/issues/261

Update github.com/karrick/godirwalk to v1.15.8
